import React, { useState } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { ACRColors, ACRTypography } from '../theme/colors';
import { ScreenLayout } from '../components/ScreenLayout';
import { ACRCard } from '../components/ACRCard';
import { ACRButton } from '../components/ACRButton';
import { ACRStateBadge } from '../components/ACRStateBadge';
import { useAssessmentStore } from '../store/assessmentStore';
import { checkAttestation } from '../api/attestation';
import { submitAssessment } from '../api/infer';
import { generateRequestId } from '../utils/uuid';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../navigation/AppNavigator';

type NavProp = NativeStackNavigationProp<RootStackParamList>;

export const ReviewScreen: React.FC = () => {
  const navigation = useNavigation<NavProp>();
  const { form, sessionId, attestation, setAttestation, setResult, reset } = useAssessmentStore();
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const isVerified = attestation?.verificationState === 'VERIFIED';

  const handleSubmit = async () => {
    setSubmitting(true);
    setError(null);

    try {
      // 1. Re-check attestation (fail-closed)
      const att = await checkAttestation();
      setAttestation(att);

      if (att.verificationState !== 'VERIFIED') {
        navigation.navigate('FailClosed');
        setSubmitting(false);
        return;
      }

      // 2. Build request
      const request = {
        contract: 'acr.cds.v1' as const,
        requestId: generateRequestId(),
        assessment: {
          patientId: sessionId,
          erStatus: form.step1.erStatus,
          prStatus: form.step1.prStatus,
          her2Status: form.step1.her2Status,
          ki67: Number(form.step1.ki67),
          stage: form.step2.stage || null,
          grade: form.step2.grade || null,
          histologicalSubtype: form.step2.histologicalSubtype || null,
          nodalStatus: form.step2.nodalStatus || null,
          age: form.step2.age ? Number(form.step2.age) : null,
          ca153: form.step3.ca153 ? Number(form.step3.ca153) : null,
          cea: form.step3.cea ? Number(form.step3.cea) : null,
          surgeryDate: form.step3.surgeryDate || null,
          bayesianEnhanced: form.step3.bayesianEnhanced,
        },
        client: {
          channel: 'MOBILE' as const,
          buildId: 'mob-v0.1.0+42',
          environment: 'EVALUATION' as const,
        },
      };

      // 3. Submit
      const response = await submitAssessment(request);
      setResult(response);
      navigation.navigate('Result');
    } catch (err: any) {
      setError(err.message || 'Submission failed');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <ScreenLayout
      title="Review"
      subtitle="Confirm entries before submission"
      bannerText="Clinical transparency: outputs are decision support only, generated by a validated rule base."
      footer={
        <>
          <ACRButton title="Edit" variant="secondary" onPress={() => navigation.navigate('Step1')} />
          <ACRButton
            title="Submit"
            variant="primary"
            disabled={!isVerified || submitting}
            onPress={handleSubmit}
          />
        </>
      }
    >
      <ACRCard title="Entered values">
        <Row label="ER / PR / HER2" value={`${form.step1.erStatus.slice(0,3)} / ${form.step1.prStatus.slice(0,3)} / ${form.step1.her2Status.slice(0,3)}`} />
        <Row label="Ki-67" value={`${form.step1.ki67} %`} />
        <Row label="Stage / Grade" value={`${form.step2.stage || '—'} / ${form.step2.grade || '—'}`} />
        <Row label="Histology" value={form.step2.histologicalSubtype || '—'} />
        <Row label="Nodal status" value={form.step2.nodalStatus || '—'} />
        <Row label="Age" value={form.step2.age || '—'} />
        <Row label="CA 15-3 / CEA" value={`${form.step3.ca153 || '—'} / ${form.step3.cea || '—'}`} />
        <Row label="Surgery date" value={form.step3.surgeryDate || '—'} />
      </ACRCard>

      <ACRCard title="Reasoning options">
        <Row label="Bayesian layer" value={form.step3.bayesianEnhanced ? 'ON' : 'OFF'} />
        <Text style={styles.hint}>Sets a request field only. No calculation occurs on the device.</Text>
      </ACRCard>

      <ACRCard title="Baseline">
        <Row
          label="Attestation"
          valueComponent={
            attestation ? (
              <ACRStateBadge state={attestation.verificationState} />
            ) : (
              <Text style={styles.muted}>Checking…</Text>
            )
          }
        />
        <Text style={styles.hint}>Reasoner v2.2.1 · OPENLLET_SWRL · ontology hash matches the accepted baseline manifest.</Text>
      </ACRCard>

      {error ? (
        <View style={styles.errorBox}>
          <Text style={styles.errorText}>{error}</Text>
        </View>
      ) : null}
    </ScreenLayout>
  );
};

const Row: React.FC<{ label: string; value?: string; valueComponent?: React.ReactNode }> = ({
  label,
  value,
  valueComponent,
}) => (
  <View style={styles.row}>
    <Text style={styles.rowLabel}>{label}</Text>
    {valueComponent || <Text style={styles.rowValue}>{value}</Text>}
  </View>
);

const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: ACRColors.line,
    borderStyle: 'dashed',
  },
  rowLabel: {
    fontSize: 11,
    color: ACRColors.ink,
  },
  rowValue: {
    fontSize: 11,
    fontWeight: '600',
    color: ACRColors.ink,
  },
  hint: {
    ...ACRTypography.hint,
    color: ACRColors.muted,
    marginTop: 4,
  },
  muted: {
    fontSize: 11,
    color: ACRColors.muted,
  },
  errorBox: {
    backgroundColor: ACRColors.stopBg,
    borderRadius: 8,
    padding: 10,
    marginTop: 10,
  },
  errorText: {
    color: ACRColors.stopBorder,
    fontSize: 11,
  },
});
