import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { ACRColors, ACRTypography } from '../theme/colors';
import { ScreenLayout } from '../components/ScreenLayout';
import { ACRCard } from '../components/ACRCard';
import { ACRSegmentedControl } from '../components/ACRSegmentedControl';
import { ACRInput } from '../components/ACRInput';
import { ACRButton } from '../components/ACRButton';
import { useAssessmentStore } from '../store/assessmentStore';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../navigation/AppNavigator';

type NavProp = NativeStackNavigationProp<RootStackParamList>;

export const Step2TumourScreen: React.FC = () => {
  const navigation = useNavigation<NavProp>();
  const { form, setStep2 } = useAssessmentStore();

  return (
    <ScreenLayout
      title="New assessment"
      subtitle="Step 2 of 3 · Tumour characteristics"
      bannerText="Clinical transparency: outputs are decision support only, generated by a validated rule base."
      steps={{ total: 3, current: 2 }}
      footer={
        <>
          <ACRButton title="Back" variant="secondary" onPress={() => navigation.goBack()} />
          <ACRButton title="Next" variant="primary" onPress={() => navigation.navigate('Step3')} />
        </>
      }
    >
      <ACRCard title="Tumour">
        <Label text="Stage" optional />
        <View style={styles.pickerShell}>
          <Text style={styles.pickerText}>{form.step2.stage || '—'}</Text>
        </View>
        <Text style={styles.hint}>Values populated from the frozen API-contract enum — no overlapping aliases.</Text>

        <Label text="Grade" optional />
        <ACRSegmentedControl
          options={['1', '2', '3']}
          selected={form.step2.grade || ''}
          onSelect={(v) => setStep2({ grade: v as '1' | '2' | '3' })}
        />

        <Label text="Histological subtype" optional />
        <View style={styles.pickerShell}>
          <Text style={styles.pickerText}>{form.step2.histologicalSubtype || '—'}</Text>
        </View>

        <Label text="Nodal status" optional />
        <ACRSegmentedControl
          options={['N0', 'N1', 'N2', 'N3']}
          selected={form.step2.nodalStatus || ''}
          onSelect={(v) => setStep2({ nodalStatus: v as 'N0' | 'N1' | 'N2' | 'N3' })}
        />

        <Label text="Age (years)" optional />
        <ACRInput
          value={form.step2.age}
          onChangeText={(t) => setStep2({ age: t })}
          keyboardType="numeric"
          hint="18–120, whole years. Age is the only demographic field the reasoner consumes."
        />
      </ACRCard>
    </ScreenLayout>
  );
};

const Label: React.FC<{ text: string; optional?: boolean }> = ({ text, optional }) => (
  <Text style={styles.label}>
    {text} {optional ? <Text style={styles.small}>· optional</Text> : null}
  </Text>
);

const styles = StyleSheet.create({
  label: {
    ...ACRTypography.label,
    marginTop: 9,
    marginBottom: 4,
  },
  small: {
    fontWeight: '400',
    color: ACRColors.muted,
  },
  pickerShell: {
    width: '100%',
    paddingVertical: 8,
    paddingHorizontal: 9,
    borderWidth: 1.4,
    borderColor: ACRColors.line,
    borderRadius: 8,
    backgroundColor: '#fff',
  },
  pickerText: {
    fontSize: 13,
    color: ACRColors.ink,
  },
  hint: {
    ...ACRTypography.hint,
    color: ACRColors.muted,
    marginTop: 3,
  },
});
