import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { ACRColors, ACRTypography } from '../theme/colors';
import { ScreenLayout } from '../components/ScreenLayout';
import { ACRCard } from '../components/ACRCard';
import { ACRInput } from '../components/ACRInput';
import { ACRButton } from '../components/ACRButton';
import { useAssessmentStore } from '../store/assessmentStore';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../navigation/AppNavigator';

type NavProp = NativeStackNavigationProp<RootStackParamList>;

export const Step3MarkersScreen: React.FC = () => {
  const navigation = useNavigation<NavProp>();
  const { form, setStep3 } = useAssessmentStore();

  return (
    <ScreenLayout
      title="New assessment"
      subtitle="Step 3 of 3 · Biomarkers and surgery"
      bannerText="Clinical transparency: outputs are decision support only, generated by a validated rule base."
      steps={{ total: 3, current: 3 }}
      footer={
        <>
          <ACRButton title="Back" variant="secondary" onPress={() => navigation.goBack()} />
          <ACRButton title="Review" variant="primary" onPress={() => navigation.navigate('Review')} />
        </>
      }
    >
      <ACRCard title="Serum markers">
        <Label text="CA 15-3 (U/mL)" optional />
        <ACRInput
          value={form.step3.ca153}
          onChangeText={(t) => setStep3({ ca153: t })}
          keyboardType="numeric"
          hint="Reference threshold 35.0 — evaluation is performed server-side."
        />

        <Label text="CEA (ng/mL)" optional />
        <ACRInput
          value={form.step3.cea}
          onChangeText={(t) => setStep3({ cea: t })}
          keyboardType="numeric"
          hint="Reference threshold 5.0 — evaluation is performed server-side."
        />
      </ACRCard>

      <ACRCard title="Surgery">
        <Label text="Surgery date" optional />
        <ACRInput
          value={form.step3.surgeryDate}
          onChangeText={(t) => setStep3({ surgeryDate: t })}
          hint="Future dates are permitted and submitted unchanged: the B3 guard is the reasoner's responsibility and must remain testable."
        />
      </ACRCard>
    </ScreenLayout>
  );
};

const Label: React.FC<{ text: string; optional?: boolean }> = ({ text, optional }) => (
  <Text style={styles.label}>
    {text} {optional ? <Text style={styles.small}>· optional</Text> : null}
  </Text>
);

const styles = StyleSheet.create({
  label: {
    ...ACRTypography.label,
    marginTop: 9,
    marginBottom: 4,
  },
  small: {
    fontWeight: '400',
    color: ACRColors.muted,
  },
});
