import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { ACRColors, ACRTypography } from '../theme/colors';
import { ScreenLayout } from '../components/ScreenLayout';
import { ACRCard } from '../components/ACRCard';
import { ACRSegmentedControl } from '../components/ACRSegmentedControl';
import { ACRInput } from '../components/ACRInput';
import { ACRButton } from '../components/ACRButton';
import { useAssessmentStore } from '../store/assessmentStore';
import { generatePatientId } from '../utils/uuid';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import type { RootStackParamList } from '../navigation/AppNavigator';

type NavProp = NativeStackNavigationProp<RootStackParamList>;

export const Step1ReceptorsScreen: React.FC = () => {
  const navigation = useNavigation<NavProp>();
  const { form, setStep1, sessionId, setSessionId } = useAssessmentStore();

  React.useEffect(() => {
    if (!sessionId) {
      setSessionId(generatePatientId());
    }
  }, [sessionId, setSessionId]);

  const isValid = form.step1.ki67 !== '' && !isNaN(Number(form.step1.ki67));

  return (
    <ScreenLayout
      title="New assessment"
      subtitle="Step 1 of 3 · Receptor status"
      bannerText="Clinical transparency: outputs are decision support only, generated by a validated rule base. Clinical judgement remains with the clinician."
      steps={{ total: 3, current: 1 }}
      footer={
        <>
          <ACRButton title="Cancel" variant="secondary" onPress={() => navigation.navigate('Welcome')} />
          <ACRButton
            title="Next"
            variant="primary"
            disabled={!isValid}
            onPress={() => navigation.navigate('Step2')}
          />
        </>
      }
    >
      <ACRCard title="Receptor status">
        <Label text="ER status" required />
        <ACRSegmentedControl
          options={['positive', 'negative']}
          selected={form.step1.erStatus}
          onSelect={(v) => setStep1({ erStatus: v as 'positive' | 'negative' })}
        />

        <Label text="PR status" required />
        <ACRSegmentedControl
          options={['positive', 'negative']}
          selected={form.step1.prStatus}
          onSelect={(v) => setStep1({ prStatus: v as 'positive' | 'negative' })}
        />

        <Label text="HER2 status" required />
        <ACRSegmentedControl
          options={['positive', 'negative']}
          selected={form.step1.her2Status}
          onSelect={(v) => setStep1({ her2Status: v as 'positive' | 'negative' })}
        />

        <Label text="Ki-67 (%)" required />
        <ACRInput
          value={form.step1.ki67}
          onChangeText={(t) => setStep1({ ki67: t })}
          keyboardType="numeric"
          hint="0–100. Luminal A < 14, Luminal B ≥ 14. Guidance only — classification is performed by the reasoner."
        />
      </ACRCard>

      <ACRCard title="Session">
        <Label text="Session ID" generated />
        <ACRInput value={sessionId} readOnly hint="Fresh UUIDv4 per assessment. Never entered, never reused, never persisted." />
      </ACRCard>
    </ScreenLayout>
  );
};

const Label: React.FC<{ text: string; required?: boolean; generated?: boolean }> = ({
  text,
  required,
  generated,
}) => (
  <Text style={styles.label}>
    {text}{' '}
    {required ? <Text style={styles.small}>· required</Text> : null}
    {generated ? <Text style={styles.small}>· generated</Text> : null}
  </Text>
);

const styles = StyleSheet.create({
  label: {
    ...ACRTypography.label,
    marginTop: 9,
    marginBottom: 4,
  },
  small: {
    fontWeight: '400',
    color: ACRColors.muted,
  },
});
